language: c
git:
  quiet: true

addons:
  apt:
    packages:
      - libpam0g-dev

compiler:
  - gcc
  - clang

before_script:
  - configure --enable-pam --enable-min-unix-id=100

script:
  - make

branches:
   only:
     - master

install: true
